### ISSUE TITLE
Zookeeper Operator upgrade fails because of readiness check in deploy file

### ISSUE THREAD

**Issue by pbelgundi** [pravega/zookeeper-operator#101]
Tried upgrading zookeeper-operator from version 0.2.4 to 0.2.5-rc0 and upgrade got stuck when this readiness check for specified in the operator manifest:
```
 readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
```
On removing this check, initial deployment and upgrade both completed successfully.
This check needs to be removed/corrected in operator deployment manifest
