### ISSUE TITLE
customize the zookeeper image repo

### ISSUE THREAD

**Issue by seecsea** [pravega/zookeeper-operator#105]
the zookeeper image is set to pravega/zookeeper:latest default
If I do not use command "make build" from Makefile myself,how can I use myself image registry just like 172.31.0.8/pravega/zookeeper:latest?
and,where I can find the Dockerfile of pravega/zookeeper:latest?
Thanks a lot!

**Comment by spiegela** [comment]
Yes, it is fine to do so.  In fact, if you use the bundled Helm chart you can set the registry/repository with `helm install --set image.repository=172.31.0.8/pravega/zookeeper`

**Comment by seecsea** [comment]
If I do not use Helm,and then how can I?

**Comment by spiegela** [comment]
@seecsea you can set the image in the zookeeper cluster spec like so:
```
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: my-zookeeper-cluster
spec:
  image: 172.31.0.8/pravega/zookeeper:latest
```
