### ISSUE TITLE
Is there a way to configure Volumeclaimtemplates in zookeeper cluster yaml

### ISSUE THREAD

**Issue by priyavj08** [pravega/zookeeper-operator#117]
I want to be able to configure my own PVC in zookeeper cluster, does the operator support it?

**Comment by pbelgundi** [comment]
Volume claim templates can be configured using the "persistence" field in the yaml file.
https://github.com/pravega/zookeeper-operator/blob/master/pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go#L366

```
persistence:
      reclaimPolicy: Delete
      spec:
           < configuration for the PVC here>
```
