### ISSUE TITLE
Leader election failing when pod restarts

### ISSUE THREAD

**Issue by AceHack** [pravega/zookeeper-operator#128]
We are running into the following known Zookeeper bug

https://issues.apache.org/jira/browse/ZOOKEEPER-2164

As a workaround, we are running the following liveness probe:

`liveness-check`
```
#!/usr/bin/env bash

OK=$(echo ruok | nc 127.0.0.1 $1)
if [ "$OK" == "imok" ]; then
	OK=$(echo mntr | nc 127.0.0.1 $1)
	STANDALONE=$'zk_server_state\tstandalone'
	FOLLOWER=$'zk_server_state\tfollower'
	LEADER=$'zk_server_state\tleader'
	FOLLOWERS=$'zk_followers\t'$2
	if [ "$2" == "0" ]; then
    if [[ "$OK" == *"$STANDALONE"* ]]; then
      echo "Standalone Found"
      exit 0
    else
      echo "ERROR: Standalone not found"
      exit 4
    fi
	else
    if [[ "$OK" == *"$FOLLOWER"* ]]; then
      echo "Follower Found"
      exit 0
    elif [[ "$OK" == *"$LEADER"* ]]; then
      if [[ "$OK" == *"$FOLLOWERS"* ]]; then
        echo "Leader Found with correct number of followers"
        exit 0
      else
        echo "ERROR: Leader Found with incorrect number of followers"
        exit 3
      fi
    else
      echo "ERROR: Leader or Follower not found"
      exit 2
    fi
	fi
else
  echo "ERROR: Not imok"
	exit 1
fi
```

`helm chart`
```
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "liveness-check {{ .Values.service.port }} {{ sub .Values.replicaCount 1 }}"
          initialDelaySeconds: 10
          failureThreshold: 12
          periodSeconds: 15
          timeoutSeconds: 10
```

The script will ensure:

- if the replica count is set to 1
  - then the 1 zookeeper instance should be running in standalone mode
- if the replica count is greater than 1
  - then all the instances should be either a leader or follower
  - if the instance is a leader
    - then the instance should make sure it has n-1 followers

if any of these checks fail then it will restart the pod

Can you please add this workaround or similar until the bug above is fixed in zookeeper?

Thanks.
