### ISSUE TITLE
Unable to configure storage resources of zookeeper PVCs

### ISSUE THREAD

**Issue by SrishT** [pravega/zookeeper-operator#177]
### Description
Unable to configure storage resources of zookeeper PVCs by specifying this value inside the manifest in the following manner at the time of deployment (i.e. the value supplied for this field does not take effect and its value is defaulted to `20Gi` by the operator).

```
  persistence:
    resources:
      requests:
        storage: 10Gi
```
