### ISSUE TITLE
ImagePullSecrets field is not supported

### ISSUE THREAD

**Issue by zmberg** [pravega/zookeeper-operator#185]
CRD ZookeeperCluster don't support ImagePullSecrets, the mirror image of the private warehouse cannot be pulled up.

```
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  namespace: default
spec:
  # Add fields here
  replicas: 3
  image:
    repository: xxxxx:8080/xxxxx/zookeeper
    tag: 3.6.1
  persistence:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "cbs"
    reclaimPolicy: Delete
    resources:
      requests:
        storage: 10Gi
```
