### ISSUE TITLE
zoo.cfg not getting modified.

### ISSUE THREAD

**Issue by gimpiron** [pravega/zookeeper-operator#224]
### Description

Hey, so im trying to deploy zookeeper cluster with the following modification;
```
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "zookeeper"
spec:
  replicas: 3
  config:
    tickTime: 2000
    initLimit: 10
    syncLimit: 5
    clientPort: 2181
    maxClientCnxns: 2000
    maxSessionTimeout: 60000000
    autopurge.snapRetainCount: 3
    autopurge.purgeInterval: 1
    preAllocSize: 131072
    snapCount: 3000000
    reconfigEnabled: true
    4lw.commands.whitelist: "*"
    dataDir: "/data/zookeeper"
```

Sadly, i cannot see my changes inside my pod at /data/cong/zoo.cfg.
Morover, I cant see the changes the zookeeper configmap:

```
zoo.cfg:
----
4lw.commands.whitelist=cons, envi, conf, crst, srvr, stat, mntr, ruok
dataDir=/data
standaloneEnabled=false
reconfigEnabled=true
skipACL=yes
metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
metricsProvider.httpPort=7000
metricsProvider.exportJvmInfo=true
initLimit=10
syncLimit=5
tickTime=2000
quorumListenOnAllIPs=false
dynamicConfigFile=/data/zoo.cfg.dynamic
```

What am I missing? are all config options are configurable? 

### Importance

blocker

### Suggestions for an improvement

More documentation about possible options and where the config file is located & used.
