### ISSUE TITLE
Storage class name not picked up

### ISSUE THREAD

**Issue by uprush** [pravega/zookeeper-operator#232]
### Description

_(Describe the feature, bug, question, proposal that you are requesting)_

### Importance

Pod created stuck at VolumeBinding. It seems the cause is storage class is not picked up when creating the pvc.

ZK spec:
```
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "reddot-zk"
  namespace: infra
spec:
  replicas: 3
  persistence:
    storageClassName: pure-block
    volumeSize: 20Gi
```

Pod creation  error
```
kubectl -n infra describe pod reddot-zk-0

Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-reddot-zk-0
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "reddot-zk-0": pod has unbound immediate PersistentVolumeClaims
```

PVC error:
```
kubectl -n infra describe pvc data-reddot-zk-0
Name:          data-reddot-zk-0
Namespace:     infra
StorageClass:
Status:        Pending
Volume:
Labels:        app=reddot-zk
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    reddot-zk-0
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  4m27s (x42 over 14m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

### Location

_(Where is the piece of code, package, or document affected by this issue?)_

### Suggestions for an improvement

_(How do you suggest to fix or proceed with this issue?)_
