### ISSUE TITLE
How should I use `imagePullSecrets` in deploying zookeeper cluster?

### ISSUE THREAD

**Issue by soleimaniamir** [pravega/zookeeper-operator#273]
Hello, I want to deploy a zookeeper cluster with operator, but I don't know where I should add imagePullSecrets in yaml. this is my deploy file:

```
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  replicas: 3
  image:
    repository: 192.168.161.187:9050/pravega/zookeeper
    tag: 0.2.9
  storageType: persistence
  persistence:
    reclaimPolicy: Delete
    spec:
      storageClassName: rancher-rbd
      resources:
        requests:
          storage: 10Gi
```

**Comment by soleimaniamir** [comment]
Hello, I want to deploy a zookeeper cluster with operator, but I don't know where I should add `imagePullSecrets` in yaml. this is my deploy file:
```
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  replicas: 3
  image:
    repository: 192.168.161.187:9050/pravega/zookeeper
    tag: 0.2.9
  storageType: persistence
  persistence:
    reclaimPolicy: Delete
    spec:
      storageClassName: rancher-rbd
      resources:
        requests:
          storage: 10Gi
```

**Comment by Prabhaker24** [comment]
@soleimaniamir image pull secret works for non-default account you can apply it like this
```
spec:
    serviceAccountName: "zookeeper"
    imagePullSecret: 
    - name: "regcred"
```

**Comment by soleimaniamir** [comment]
@Prabhaker24  This is `rbac.yaml` that I applied before deploying zookeeper:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-operator

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zookeeper-operator
rules:
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zookeeper-operator-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: zookeeper-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: zookeeper-operator
  apiGroup: rbac.authorization.k8s.io
```
then I changed my `deploy.yml` like here:
```
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  replicas: 3
  serviceAccountName: "zookeeper-operator"
  imagePullSecret: 
  - name: "nexuspullsecret"
  image:
    repository: 192.168.161.187:9050/pravega/zookeeper
    tag: 0.2.9
  storageType: persistence
  persistence:
    reclaimPolicy: Delete
    spec:
      storageClassName: rancher-rbd
      resources:
        requests:
          storage: 10Gi
```
but there is error `no basic auth credentials`
