### ISSUE TITLE
Support configure annotations for zookeeper pod again

### ISSUE THREAD

**Issue by fokkoru** [pravega/zookeeper-operator#274]
### Description

It looks to me like a bug. Could be related to #125, #249, #260 

I try to apply `kubectl apply -f zk.yam` the following config on GKE
```
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  replicas: 3
  persistence:
    spec:
      storageClassName: pd-ssd
      resources:
        requests:
          storage: 500Gi
  pod:
    annotations:
      ad.datadoghq.com/zookeeper.check_names: '["zk"]'
      ad.datadoghq.com/zookeeper.init_configs: '[{}]'
      ad.datadoghq.com/zookeeper.instances: '[{"host": "%%host%%", "port": "2181"}]'
```
but after I can't find those annotations on pods. What did I wrong? A version of zookeeper-operator is 0.2.9.

### Importance

must-have

### Location

Configure the annotations of .spec.pod.annotations, but check the zookeeper instance, annotations don't appear in the pod spec.

### Suggestions for an improvement

Can we use .spec.pod.annotations to configure the zookeeper pods annotations?
