### ISSUE TITLE
Persistence PVC not working

### ISSUE THREAD

**Issue by ghahramani** [pravega/zookeeper-operator#284]
### Description

Hi,
I have installed istio and tried to deploy zookeeper in my cluster (I am using kubespray with two nodes and local-storage). The PVC cannot be created and `kubectl describe pvc data-zookeepr-0 -n messaging` returns this error:

```
Normal  WaitForFirstConsumer  3m9s (x82 over 23m)  persistentvolume-controller  waiting for first consumer to be created before binding
``` 

and the statefulset shows error below:

```
create Pod zookeeper-0 in StatefulSet zookeeper failed error: pods "zookeeper-0" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.initContainers[0].securityContext.runAsNonRoot: Invalid value: false: must be true spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added]
```

![image](https://user-images.githubusercontent.com/1059436/101997084-35e30f00-3ccc-11eb-8229-1f86dc655a72.png)

Here is my config

```
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  namespace: messaging
spec:
  replicas: 3
  pod:
    serviceAccountName: sa-zookeeper
    securityContext:
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
  config:
    initLimit: 10
    tickTime: 2000
    syncLimit: 5
    quorumListenOnAllIPs: true
  storageType: persistence
  persistence:
    reclaimPolicy: Delete
    spec:
      storageClassName: local-storage
      resources:
        requests:
          storage: 9007Mi
```
And here is my rbac configs as I need to give some permission for istio side car containers

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-zookeeper
  namespace: messaging
spec:
  privileged: true
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: true
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  allowedCapabilities:
    - NET_RAW
    - NET_ADMIN
  # Allow core volume types.
  volumes:
    - downwardAPI
    - emptyDir
    - secret
    - configMap
    - persistentVolumeClaim
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'RunAsAny'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-zookeeper
  namespace: messaging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-zookeeper
  namespace: messaging
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-zookeeper
    resources:
      - podsecuritypolicies
      - poddisruptionbudgets
    verbs:
      - use
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-zookeeper
  namespace: messaging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-zookeeper
subjects:
  - kind: ServiceAccount
    name: sa-zookeeper
    namespace: messaging
```

Now, if I change the storage type to `ephemeral`, everything works
### Importance

It is a blocker right now for me. I cannot deploy it at all unless I use the other storageType

### Suggestions for an improvement

I have no idea how to fix it, it seems the initContainer does not accept my serviceAccountName so it does not have permission to create the PVC, this is my only guess.
