### ISSUE TITLE
Is there any way to deploy crd and operator seperatly? 

### ISSUE THREAD

**Issue by krishnachalla-hv** [pravega/zookeeper-operator#298]
Right now If only want to deploy crd I think that is not possible currently due helm templates values are used in crd file. Is there any way to do that. Basically I am developing multi tenancy application for that I am deploying zookeeper operator per namespace.

Lets say I installed the zookeeper operator in **tenant-1** namespace like below:
`helm install -f ~/my-values.yaml t0 -n tenant-1 .`
values for **t0** release:
```
zookeeper-operator:
  watchNamespace: "tenant-1"
  crd:
    create: true
```
Again Installing it in **tenant-2** namespace like below:
`helm install -f ~/my-values.yaml t1 -n tenant-2 .`
values for **t1** release:
```
zookeeper-operator:
  watchNamespace: "tenant-2"
  crd:
    create: false
```
When I uninstall **t0** release in **tenant-1** namespace it terminates zookeeper pods in **tenant-2** namespace also.
But when I uninstall **t1** release it won't terminate the zookeeper pods in **tenant-1** namespace.
