### ISSUE TITLE
wrong PV failure-domain.beta.kubernetes.io/zone

### ISSUE THREAD

**Issue by mike-serchenia** [pravega/zookeeper-operator#311]
### Description

GKE cluster

I'm creating ZookeeperCluster with the following config
```yaml
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "example"
spec:
  replicas: 3
  pod:
    nodeSelector:
      cloud.google.com/gke-nodepool: zoo-node-pool
  storageType: persistence
  persistence:
    spec:
      reclaimPolicy: delete
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
      accessModes:
        - ReadWriteOnce     
```
The node pool has both `failure-domain.beta.kubernetes.io/region=us-east4` and `,failure-domain.beta.kubernetes.io/zone=us-east4-a` labels. While PV was created with
```yaml
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-east4-b
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-east4
```
as a result `Cannot schedule pods: node(s) had volume node affinity conflict.` 

The cluster has a few node-pools, one of them actually has `failure-domain.beta.kubernetes.io/zone=us-east4-b`
