### ISSUE TITLE
Missing volumeMounts after Helm install

### ISSUE THREAD

**Issue by runzhliu** [pravega/zookeeper-operator#415]
### Description

We find the wrong render result by the origin template the values with `volumeMounts` filled.

```yaml
# Source: Values.yaml
...
hooks:
  image:
...
containers: []
volumes: [{"name":"zk-persistent-storage","persistentVolumeClaim":{"claimName":"zk-pv-claim"}}]
volumeMounts: [{"mountPath":"/var/lib/zk","name":"zk-persistent-storage"}]
initContainers: []
---
# Source: zookeeper/templates/zookeeper.yaml
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: zookeeper
  namespace: default
 ...
  # missing volumeMounts
  volumes:
    - name: zk-persistent-storage
      persistentVolumeClaim:
        claimName: zk-pv-claim
    - mountPath: /var/lib/zk
      name: zk-persistent-storage
```

### Location

`charts/zookeeper/templates/`
