### ISSUE TITLE
changing replicas sequence test `1 -> 3 -> 1 -> 3` not works on latest step, Second ZK pod doesn't starts due to 'java.lang.RuntimeException: My id 2 not in the peer list' exception

### ISSUE THREAD

**Issue by Slach** [pravega/zookeeper-operator#448]
### Description

Multiple scale-up, scale-down operation doesn't wok
Looks similar with https://github.com/pravega/zookeeper-operator/issues/315, but increase `initialDelaySeconds: 30` doesn't help

### Importance

It is critical important for our environment, we attempt to scale-up during heavy workloads and scale-down to decrease costs.

### Steps to reproduce
we use latest `0.2.13` release

and use two following manifests

**zookeeper-operator-1-node.yaml**
```yaml
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  labels:
    app: zookeeper-operator
spec:
  replicas: 1
  image:
    repository: pravega/zookeeper
    tag: 0.2.13
  labels:
    app: zookeeper-operator
  storageType: persistence
  probes:
    readinessProbe:
      initialDelaySeconds: 30
  persistence:
    reclaimPolicy: Retain
    spec:
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
```

**zookeeper-operator-3-node.yaml** (same manifest only changed `replicas: 3`)

```yaml
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  labels:
    app: zookeeper-operator
spec:
  replicas: 3
  image:
    repository: pravega/zookeeper
    tag: 0.2.13
  labels:
    app: zookeeper-operator
  storageType: persistence
  probes:
    readinessProbe:
      initialDelaySeconds: 30
  persistence:
    reclaimPolicy: Retain
    spec:
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
```

simple bash script to reproduce
```bash
kubectl delete ns test
kubectl create ns test 

kubectl apply -n test -f zookeeper-operator-1-node.yaml
sleep 300 
kubectl get pods -n test -l app=zookeeper # return zookeeper-0 in running state

kubectl apply -n test -f zookeeper-operator-3-node.yaml
sleep 300 
kubectl get pods -n test -l app=zookeeper # return zookeeper-0, zookeeper-1, zookeeper-2 in running state

kubectl apply -n test -f zookeeper-operator-1-node.yaml
sleep 300 
kubectl get pods -n test -l app=zookeeper # return zookeeper-0 in running state

# error HERE !!
kubectl apply -n test -f zookeeper-operator-3-node.yaml
sleep 300 
kubectl get pods -n test -l app=zookeeper # return zookeeper-0 in running and ready state, zookeeper-1 in CrashLoopBack

```

### Error message

```
2022-03-29 10:22:12,345 [myid:2] - ERROR [main:QuorumPeerMain@113] - Unexpected exception, exiting abnormally
java.lang.RuntimeException: My id 2 not in the peer list
at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:1077)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:227)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:136)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
2022-03-29 10:22:12,346 [myid:2] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.                                                                            2022-03-29 10:22:12,348 [myid:2] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1
```
