### ISSUE TITLE
Want to set publishNotReadyAddresses: true in statefulset's headless service permanenetly

### ISSUE THREAD

**Issue by subhranil05** [pravega/zookeeper-operator#545]
### Description

I am using latest zookeeper-operator/zookeeper helm charts. Here I want to set publishNotReadyAddresses: true in headless service for zookeeper permanenetly.
I'm using annotaions `Service.spec.publishNotReadyAddresses: "true" `in headless service through values file, but seems not doing the job, please let me know if any other way to do it
### Importance

Zookeeper followers couldn't connect the leader, failing all the time with unknow host exception

### Location

_(Where is the piece of code, package, or document affected by this issue?)_

### Suggestions for an improvement

Option to update in spec of headless service with values file

**Comment by subhranil05** [comment]
@AKamyshnikova @anishakj 
Mentioning your names as active contributor to this repo, thanks for the cooperating.
Guys could you please guide me on this? its really urgent requirement for me
I need to add `publishNotReadyAddresses: true` on spec section of headless service permanently

**Comment by AKamyshnikova** [comment]
@subhranil05 Hi! Creation of headless service is done here https://github.com/pravega/zookeeper-operator/blob/72bea545a73130c82b530e508a2a14daaa824435/pkg/zk/generators.go#L239

**Comment by sys-liqian** [comment]
add 'publishNotReadyAddresses: true' to headless svc may cause zk server is unable to join quorum after connection broken to other peers

**Comment by subhranil05** [comment]
@sys-liqian without that there is failure for follower to join leader and timeout, any alternatives to fix this?

**Comment by sys-liqian** [comment]
@subhranil05 can you provide the zookeeper config from /data/config/zoo.cfg

**Comment by subhranil05** [comment]
@sys-liqian yeah domain is cluster.local and its correct for me
here is the config I'm using
```
config:
    additionalConfig:
      portUnification: "false"
      secureClientPort: "2281"
      serverCnxnFactory: org.apache.zookeeper.server.NettyServerCnxnFactory
      ssl.quorum.hostnameVerification: "false"
      ssl.quorum.keyStore.location: /path/keystore.jks
      ssl.quorum.keyStore.password: <password>
      ssl.quorum.trustStore.location: /path/truststore.jks
      ssl.quorum.trustStore.password: <password>
      sslQuorum: "true"
    autoPurgePurgeInterval: 1
    autoPurgeSnapRetainCount: 3
    commitLogCount: 500
    globalOutstandingLimit: 1000
    initLimit: 10
    maxClientCnxns: 60
    maxSessionTimeout: 40000
    minSessionTimeout: 4000
    preAllocSize: 65536
    snapCount: 10000
    snapSizeLimitInKb: 4194304
    syncLimit: 5
    tickTime: 2000
```
