### ISSUE TITLE
Support to Add secureClientPort '2281' to zookeeper Client Service

### ISSUE THREAD

**Issue by subhranil05** [pravega/zookeeper-operator#553]
### Description

I'm working on TLS implementation in zookeeper and abled to implement TLS in zookeeper qourum with below configs
```
config:
    additionalConfig:
      portUnification: "false"
      secureClientPort: "2281"
      serverCnxnFactory: org.apache.zookeeper.server.NettyServerCnxnFactory
      ssl.quorum.hostnameVerification: "false"
      ssl.quorum.keyStore.location: /path/keystore.jks
      ssl.quorum.keyStore.password: <password>
      ssl.quorum.trustStore.location: /path/truststore.jks
      ssl.quorum.trustStore.password: <password>
      sslQuorum: "true"
```
Now I have also added new port 2281 which is tls client port. 2181 default port is already there.
I have added this port as container port in zookeeperCluster.yaml and statefulset also reflecting that.

Now we need to permanently expose this port (2281) in zookeeper-client-service, where currently default port 2181 is present.
Please guide/help me to implement this, there is no way now to add the port to service permanently
### Importance

To run the zookeeper server-client connection through a secure port

### Location
https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/values.yaml
https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/templates/zookeeper.yaml

### Suggestions for an improvement

Need an option to expose 2281 port to zookeeper-client-svc
