### ISSUE TITLE
There doesnt seem to be a way to specify a SC for Zookeeper

### ISSUE THREAD

**Issue by OteemoSanjay** [pravega/zookeeper-operator#622]
### Description

Based on the halm values.  There is no way to details a Pv/ PVC or even a SC for the zookeeper operator

### Importance

_Would be good to have to incorporate zookeeper to whatever storage is being used.  Either EFS or NFS or other_

### Suggestions for an improvement

_Update the values.yaml to allow dynamic provisioning _

**Comment by larsskj** [comment]
No - why should there be? The Zookeeper operator does not use persistent storage.

A Zookeeper _cluster_ needs persistent storage - and that is already configurable in the cluster Helm chart.

**Comment by qdrddr** [comment]
```yaml 
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "zookeeper-test"
spec:
  replicas: 3
  #https://hub.docker.com/r/pravega/zookeeper/tags?name=0.2.
  image:
    repository: pravega/zookeeper
    tag: 0.2.15
  storageType: persistence
  persistence:
    reclaimPolicy: Delete
    spec:
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi
```
