### ISSUE TITLE
storageClassName not applied from ZookeeperCluster yaml

### ISSUE THREAD

**Issue by mdharper** [pravega/zookeeper-operator#75]
I've been trying to get the example zk cluster running while specifying a specific storageClass via the PersistentVolumeClaimSpec that's under "persistence" in the ZookeeperCluster yaml and it doesn't appear to be applying that field. It keeps attempting to apply the cluster's default storage class.

```
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "example"
  namespace: "default"
spec:
  persistence:
    storageClassName: cluster-storage
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
  size: 3
```

**Comment by priyavj08** [comment]
I am facing the same issue. How to specify custom storageClassName to be used in PVC that gets automatically created?

thanks

**Comment by spiegela** [comment]
@vgupta-mickey I thought we had a fix for this issue. Could this be a regression?

**Comment by priyavj08** [comment]
hi, any update on this. appreciate your help

**Comment by ksponomarev** [comment]
Hi, I have the same problem with `persistent volumes`
My `zk.yml` looks like  this:
```yaml
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeepercluster
  namespace: kafka
spec:
  replicas: 3
  persistence:
    reclaimPolicy: "Delete"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1G
      storageClassName: "fast-disks"
```
After deploy I have `PVC` in Pending status and  looks like this:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2019-12-05T12:46:44Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: zookeepercluster
  name: data-zookeepercluster-0
  namespace: kafka
  resourceVersion: "3158574"
  selfLink: /api/v1/namespaces/kafka/persistentvolumeclaims/data-zookeepercluster-0
  uid: 1501725a-493c-4d30-bd15-b1c86541db34
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
status:
  phase: Pending
```

Thanks

**Comment by hayorov** [comment]
100% working CR example is

```
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: XXX
spec:
  replicas: 3
  persistence:
    resources:
      requests:
        storage: 100Gi
      storage: 3G
```

tested with `zookeeper-operator-0.0.2` from repo `banzaicloud-stable/zookeeper-operator`

**Comment by cyberjso** [comment]
Hello everyone, 

I had exactly same issue. I tried to apply the following config for my zookeeper cluster:

```yaml
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  namespace: development
spec:
  replicas: 1
  persistence:
    reclaimPolicy: "Delete"
    resources:
      storageClassName: local-storage
      requests:
        storage: 10Gi
```
Even after doing this, the persistent volume claim was not able to bound. Somehow, even setting the storageClassName attribute It was not able to bind to my local-storage volume definition. The message I was having on the persistent volume claim was this one:

```
Name:          data-zookeeper-0
Namespace:     development
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=zookeeper
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    zookeeper-0
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  2m5s (x2001 over 8h)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

```
It only worked after i set my local storage [definition to default](https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/), something similar to what @the-flow-bot did. After these changes, It was able to the default option.

Anyway, Thanks @hayorov and @the-flow-bot ! The instructions you provided here saved me hours of work!
